// src/lib/components/ui/DocumentTabs.svelte
<script lang="ts">
  import { Circle, X } from "lucide-svelte";
  import { press } from "$lib/motion/actions";
  import { flipLayout } from "$lib/motion/flip";

  interface Tab {
    path: string;
    name: string;
    dirty: boolean;
  }

  let {
    tabs,
    activePath,
    compact = false,
    onswitch,
    onclose,
  }: {
    tabs: Tab[];
    activePath: string;
    compact?: boolean;
    onswitch: (path: string) => void;
    onclose: (path: string) => void;
  } = $props();
</script>

<div
  class="flex min-w-0 flex-1 gap-0.5 overflow-x-auto px-1.5"
  class:h-9={compact}
  class:h-10={!compact}
  role="tablist"
  aria-label="Open documents"
>
  {#each tabs as tab}
    <div
      use:flipLayout={tabs.map((entry) => entry.path).join("|")}
      class="document-tab ui-interactive group my-1 flex min-w-28 max-w-48 shrink-0 items-center gap-1.5 rounded-lg px-2.5 text-xs {tab.path === activePath ? 'ui-glass-control--active text-base-content' : ''}"
      class:ui-text-tertiary={tab.path !== activePath}
      role="tab"
      tabindex="0"
      aria-selected={tab.path === activePath}
      onclick={() => onswitch(tab.path)}
      onkeydown={(event) => {
        if (event.key === "Enter" || event.key === " ") {
          event.preventDefault();
          onswitch(tab.path);
        }
      }}
    >
      {#if tab.dirty}
        <Circle class="size-1.5 shrink-0 fill-current text-primary" />
      {/if}
      <span class="min-w-0 flex-1 truncate">{tab.name}</span>
      <button
        use:press
        type="button"
        class="tab-close ui-glass-hover ui-interactive flex size-6 shrink-0 items-center justify-center rounded-md {tab.path === activePath ? '' : 'opacity-0 group-hover:opacity-100 focus:opacity-100'}"
        onclick={(event) => {
          event.stopPropagation();
          onclose(tab.path);
        }}
        aria-label={`Close ${tab.name}`}
      >
        <X class="ui-icon ui-icon--sm" />
      </button>
    </div>
  {/each}
</div>

// src/features/workspace/document-tabs.tsx
import { ContextMenu, ContextMenuContent, ContextMenuItem, ContextMenuSeparator, ContextMenuTrigger } from "@/components/ui/context-menu";
import { FileTypeIcon } from "@/components/ui/file-type-icon";
import { fileStem } from "@/domain/workspace";
import { useWorkspace } from "@/app/workspace-context";
import { XIcon } from "@phosphor-icons/react";

export function DocumentTabs() {
  const { controller, state } = useWorkspace();
  if (!state.tabs.length) return null;

  return (
    <div className="no-scrollbar flex min-w-0 items-center gap-1 overflow-x-auto">
      {state.tabs.map((tab) => {
        const active = tab.path === state.activePath;
        const tabIndex = state.tabs.findIndex((candidate) => candidate.path === tab.path);
        const hasOtherTabs = state.tabs.length > 1;
        const hasTabsToRight = tabIndex < state.tabs.length - 1;
        const closeOthers = state.tabs
          .filter((candidate) => candidate.path !== tab.path)
          .map((candidate) => candidate.path);
        const closeToRight = state.tabs.slice(tabIndex + 1).map((candidate) => candidate.path);

        return (
          <ContextMenu key={tab.path}>
            <ContextMenuTrigger asChild>
              <div
                className={`group/tab relative flex min-w-28 max-w-52 items-center rounded-md transition-colors ${
                  active
                    ? "bg-muted text-foreground"
                    : "text-muted-foreground hover:bg-muted/60 hover:text-foreground"
                }`}
              >
                <button
                  type="button"
                  className="flex min-w-0 flex-1 items-center gap-2 px-3 py-2 text-left text-xs active:translate-y-px"
                  onClick={() => controller.switchTab(tab.path)}
                >
                  <FileTypeIcon
                    name={tab.name}
                    className="size-3.5 shrink-0 text-muted-foreground"
                    fallbackWeight={active ? "duotone" : "regular"}
                  />
                  <span className="truncate">{fileStem(tab.name)}</span>
                  {tab.dirty ? <span className="text-muted-foreground">*</span> : null}
                </button>
                <button
                  type="button"
                  className={`mr-1 flex size-6 shrink-0 items-center justify-center rounded-md text-muted-foreground transition-[opacity,background-color,color] hover:bg-muted hover:text-foreground focus:opacity-100 ${
                    active ? "opacity-65" : "opacity-0 group-hover/tab:opacity-65"
                  }`}
                  onClick={() => controller.closeTab(tab.path)}
                  aria-label={`Close ${tab.name}`}
                >
                  <XIcon className="size-3" />
                </button>
              </div>
            </ContextMenuTrigger>
            <ContextMenuContent className="min-w-52">
              <ContextMenuItem onSelect={() => controller.closeTab(tab.path)}>Close</ContextMenuItem>
              <ContextMenuItem
                disabled={!hasOtherTabs}
                onSelect={() => controller.closeTabs(closeOthers)}
              >
                Close Others
              </ContextMenuItem>
              <ContextMenuItem
                disabled={!hasTabsToRight}
                onSelect={() => controller.closeTabs(closeToRight)}
              >
                Close to the Right
              </ContextMenuItem>
              <ContextMenuSeparator />
              <ContextMenuItem
                onSelect={() => controller.closeTabs(state.tabs.map((item) => item.path))}
              >
                Close All Tabs
              </ContextMenuItem>
            </ContextMenuContent>
          </ContextMenu>
        );
      })}
    </div>
  );
}
